<?php
// Lesson bodies for the demo catalogue, keyed by lesson slug: [type, video URL (or ''), HTML body].
// Used by seed.php, and by update-content.php to refresh lessons that already exist.
$JS = 'https://www.youtube.com/watch?v=W6NZfCO5SIk';
$PY = 'https://www.youtube.com/watch?v=_uQrJ0TkZlc';
$SQL = 'https://www.youtube.com/watch?v=HXV3zeQKqGY';

$L = [
  'welcome' => ['article', '', '<h2>Welcome to LearnSphere</h2><p>LearnSphere is a self-paced learning platform. Every course is split into <strong>modules</strong>, and every module into short <strong>lessons</strong> you can finish in one sitting.</p><h3>What you can do here</h3><ul><li>Enroll in courses and pick up exactly where you left off</li><li>Take quizzes to check your understanding</li><li>Keep private notes on any lesson</li><li>Ask the <strong>AI Tutor</strong> when you get stuck</li><li>Earn a certificate anyone can verify online</li></ul><p>Take five minutes to finish this lesson, then move on to <em>How the Platform Works</em>.</p>'],
  'how-it-works' => ['article', '', '<h2>How the platform works</h2><p>Your progress is saved automatically. A lesson counts as complete when you press <strong>Mark complete</strong>; once every required lesson in a course is complete, the course is finished and your certificate is issued.</p><h3>Progress and quizzes</h3><p>Quizzes are attached to lessons. You need <strong>70%</strong> to pass, and most quizzes allow a limited number of attempts, so read the lesson first.</p><h3>Certificates</h3><p>Each certificate has a unique verification code. Anyone can check it on the public <em>Verify</em> page without signing in.</p><h3>Getting help</h3><ol><li>Re-read the lesson and its resources.</li><li>Write down your question in your notes.</li><li>Ask the AI Tutor, which answers using the lesson you are on.</li></ol>'],
  'first-steps' => ['article', '', '<h2>Your first steps</h2><p>Let us do a quick end-to-end run so nothing about the platform surprises you later.</p><ol><li><strong>Enroll</strong> in a course from the catalogue.</li><li><strong>Open a lesson</strong> and read or watch it through.</li><li><strong>Add a note</strong> capturing the one idea worth remembering.</li><li><strong>Take the quiz</strong> if the lesson has one.</li><li><strong>Mark the lesson complete</strong> and continue to the next.</li></ol><p>Tip: short, regular sessions beat long marathons. Fifteen focused minutes a day adds up quickly.</p>'],

  'variables' => ['video', $JS, '<h2>Variables and types</h2><p>A variable is a named container for a value. Modern JavaScript uses <code>let</code> and <code>const</code>.</p><pre><code>const name = "Ada";   // cannot be reassigned\nlet score = 10;        // can be reassigned\nscore = score + 5;</code></pre><h3>Primitive types</h3><ul><li><code>string</code>, <code>number</code>, <code>boolean</code></li><li><code>null</code> and <code>undefined</code></li><li><code>bigint</code> and <code>symbol</code></li></ul><p>Use <code>typeof value</code> to inspect a type. Prefer <code>const</code> by default and reach for <code>let</code> only when a value must change. Avoid <code>var</code>, which is function scoped and easy to misuse.</p><h3>Watch out</h3><p>Use <code>===</code> instead of <code>==</code> to avoid surprising type coercion, for example <code>0 == false</code> is true but <code>0 === false</code> is false.</p>'],
  'functions' => ['video', $JS, '<h2>Functions</h2><p>Functions package reusable behaviour. You can declare them or write them as arrow functions.</p><pre><code>function add(a, b) { return a + b; }\nconst multiply = (a, b) =&gt; a * b;\n\nconsole.log(add(2, 3), multiply(2, 3));</code></pre><h3>Closures</h3><p>A function remembers the variables around it when it was created:</p><pre><code>function counter() {\n  let n = 0;\n  return () =&gt; ++n;\n}\nconst next = counter();\nnext(); // 1\nnext(); // 2</code></pre><h3>Higher-order functions</h3><p>Functions are values. <code>map</code>, <code>filter</code> and <code>reduce</code> take a function and apply it to each item of an array. They are the everyday tools for transforming data.</p>'],
  'async' => ['article', '', '<h2>Promises and async/await</h2><p>Network calls and timers finish later. A <strong>Promise</strong> represents that future result and is either pending, fulfilled or rejected.</p><pre><code>fetch("/api/courses")\n  .then((res) =&gt; res.json())\n  .then((data) =&gt; console.log(data))\n  .catch((err) =&gt; console.error(err));</code></pre><h3>async / await</h3><p>The same code reads top to bottom with <code>async</code> and <code>await</code>:</p><pre><code>async function load() {\n  try {\n    const res = await fetch("/api/courses");\n    return await res.json();\n  } catch (err) {\n    console.error(err);\n  }\n}</code></pre><p>Remember that an <code>async</code> function always returns a Promise, and that <code>await</code> only pauses that function, not the whole program.</p>'],

  'select' => ['video', $SQL, '<h2>SELECT basics</h2><p>SQL asks a database questions. The core statement is <code>SELECT</code>.</p><pre><code>SELECT title, difficulty\nFROM courses\nWHERE difficulty = \'beginner\'\nORDER BY title\nLIMIT 10;</code></pre><h3>The building blocks</h3><ul><li><code>SELECT</code> chooses the columns</li><li><code>FROM</code> chooses the table</li><li><code>WHERE</code> filters rows</li><li><code>ORDER BY</code> sorts, and <code>LIMIT</code> caps the result</li></ul><p>Read a query in the order it runs: <em>FROM, WHERE, SELECT, ORDER BY, LIMIT</em>. That mental model makes long queries much easier to debug.</p>'],
  'joins' => ['article', '', '<h2>Joins explained</h2><p>Real data is spread over several tables. A <strong>join</strong> combines rows using a shared key.</p><pre><code>SELECT u.display_name, c.title\nFROM enrollments e\nJOIN users u   ON u.id = e.user_id\nJOIN courses c ON c.id = e.course_id;</code></pre><h3>Common join types</h3><ul><li><strong>INNER JOIN</strong>: only rows that match in both tables</li><li><strong>LEFT JOIN</strong>: every row from the left table, matched or not</li><li><strong>RIGHT JOIN</strong>: the mirror image of LEFT</li></ul><p>Use a LEFT JOIN when you want to keep rows that have no match, for example users who have not enrolled in anything yet.</p>'],

  'setting-up-python' => ['video', $PY, '<h2>Setting up Python</h2><p>You need three things: Python, a virtual environment and an editor or notebook.</p><pre><code>python -m venv .venv\nsource .venv/bin/activate      # Windows: .venv\\Scripts\\activate\npip install pandas matplotlib jupyter\njupyter notebook</code></pre><p>A virtual environment keeps each project&#8217;s packages separate, which prevents version clashes later. Create a notebook, run <code>print("hello")</code>, and you are ready for the next lesson.</p>'],
  'dataframes' => ['video', $PY, '<h2>Working with DataFrames</h2><p>A pandas <strong>DataFrame</strong> is a table with labelled columns.</p><pre><code>import pandas as pd\n\ndf = pd.DataFrame({\n  "course": ["Python", "SQL", "UX"],\n  "hours": [4, 2, 2.5],\n})\n\ndf[df["hours"] &gt; 2]          # filter rows\ndf["hours"].mean()             # summarise a column\ndf.sort_values("hours")        # sort</code></pre><p>Most analysis is a chain of small steps like these: select, filter, group, summarise.</p>'],
  'cleaning-data' => ['article', '', '<h2>Cleaning messy data</h2><p>Real datasets are rarely tidy. Budget most of your time for cleaning.</p><ul><li><strong>Missing values:</strong> <code>df.isna().sum()</code> to find them, then <code>dropna()</code> or <code>fillna()</code></li><li><strong>Duplicates:</strong> <code>df.drop_duplicates()</code></li><li><strong>Wrong types:</strong> <code>pd.to_datetime()</code> and <code>astype()</code></li><li><strong>Inconsistent text:</strong> <code>str.strip().str.lower()</code></li></ul><p>Always look at the data before and after each step, and never overwrite your raw file.</p>'],
  'visualising-results' => ['video', $PY, '<h2>Visualising results</h2><p>A good chart answers one question clearly.</p><pre><code>import matplotlib.pyplot as plt\n\ndf.plot(kind="bar", x="course", y="hours", legend=False)\nplt.title("Hours per course")\nplt.ylabel("Hours")\nplt.tight_layout()\nplt.show()</code></pre><p>Choose the chart for the question: bars to compare categories, lines for change over time, scatter plots for relationships. Always label axes and give the chart a title.</p>'],

  'what-is-ux' => ['article', '', '<h2>What is UX?</h2><p><strong>User experience</strong> is how a person feels while getting something done with your product. <strong>UI</strong> is only the visible layer of that: colours, type and layout.</p><h3>The core loop</h3><ol><li>Understand who the users are and what they need</li><li>Sketch possible solutions</li><li>Test them with real people</li><li>Improve and repeat</li></ol><p>Most usability problems are found by watching just five people try to complete a task.</p>'],
  'wireframing' => ['article', '', '<h2>Wireframing</h2><p>A wireframe is a low-fidelity layout that shows structure and flow, not styling. Because it is cheap to change, you can test ideas before investing in visual design.</p><h3>How to start</h3><ul><li>List the user&#8217;s goal for the screen</li><li>Place the primary action first and make it obvious</li><li>Use boxes and labels only, with no colour</li><li>Walk a friend through it and note where they hesitate</li></ul><p>Pen and paper is a perfectly good wireframing tool.</p>'],
];

// Reference reading per lesson (real, stable docs). Appended as the 4th element: list of "Title|url".
$R = [
  "js" => ["MDN JavaScript Guide|https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide"],
  "py" => ["Python Tutorial|https://docs.python.org/3/tutorial/", "pandas Getting Started|https://pandas.pydata.org/docs/getting_started/index.html"],
  "sql" => ["PostgreSQL SQL Tutorial|https://www.postgresql.org/docs/current/tutorial-sql.html"],
  "ux" => ["10 Usability Heuristics|https://www.nngroup.com/articles/ten-usability-heuristics/"],
];
$group = ["variables"=>"js","functions"=>"js","async"=>"js","select"=>"sql","joins"=>"sql","setting-up-python"=>"py","dataframes"=>"py","cleaning-data"=>"py","visualising-results"=>"py","what-is-ux"=>"ux","wireframing"=>"ux"];
foreach ($L as $slug => &$row) { $row[3] = isset($group[$slug]) ? $R[$group[$slug]] : []; }
unset($row);
return $L;
